import { Box, Container, Grid, Typography } from "@mui/material";

const listRender = [
  {
    title: "Access",
    content:
      "Tokenization allows for minimum fractional ownership, allowing investments in Kamaleont for any budget. ",
  },
  {
    title: "Aligned incentives",
    content:
      "Considering investors enter at a company ownership level, both investor and team incentives are aligned. Different from traditional investment funds where investment teams are rewarded by fees, al income generated by the company is shared between all owners, whether team or investors, based on their ownership participation.",
  },
  {
    title: "Risk management",
    content:
      "By investing at a company level, KLT tokens represent future expectations of revenue/profit much like a company’s stock, therefore presenting a long-term investing strategy. This allows the company to invest without the risks of short-term volatilities or the need for emergency liquidation of assets.",
  },
  {
    title: "Simplification",
    content:
      "Kamaleont’s structure, team and value proposition is ideal for investors lacking knowledge and/or required time needed to invest right. ",
  },
  {
    title: "Liquidity",
    content:
      "Private fund investing is usually illiquid, and investors must wait for the investment period to end, to recoup their capital. With Kamaleont, tokens can be sold at any moment in time, ensuring true liquidity for investors, even if Kamaleont Portfolio owns illiquid assets, leveraging on one of the great benefits of blockchain technology.",
  },
  {
    title: "Transparency",
    content:
      "In the blockchain ecosystem all transactions are visible, trackable and immutable, ensuring total transparency for investors.",
  },
  {
    title: "Global investments",
    content:
      "As Kamaleont invests in projects developed anywhere in the world, investors (who reside in crypto trading approved countries) will be investing all over, greatly simplifying personal taxation and legally compliant structures.",
  },
];

function Adventages({ id }) {
  return (
    <Box id={id} sx={{ background: "#FAFAFA" }}>
      <Container
        sx={{
          pb: 10,
          color: "botonHeader.main",
        }}
        maxWidth="xl"
      >
        {/* TITLE */}
        <Box component="div">
          <Typography
            sx={{
              fontWeight: "bold",
              fontSize: "32px",
              marginBottom: "20px",
              paddingTop: "42px",
            }}
          >
            BENEFITS
          </Typography>
          <Box sx={{ margin: "10px 0px" }}>
            <hr className="hr-barra" />
          </Box>
        </Box>

        <Grid container sx={{ justifyContent: "center" }} spacing={4}>
          {listRender.map((e, i) => (
            <Grid
              key={i}
              item
              xs={12}
              sm={6}
              md={6}
              lg={4}
              xl={4}
              data-aos="flip-left"
              data-aos-duration="1000"
            >
              <Box
                sx={{
                  background: "#fff",
                  borderRadius: "30px",
                  padding: "20px",
                  minHeight: { xs: "300px", md: "250px" },
                }}
              >
                <Box component="div">
                  <Typography
                    sx={{
                      fontWeight: "bold",
                      fontSize: "25px",
                      marginBottom: "20px",
                    }}
                  >
                    {e.title}
                  </Typography>
                  <Box sx={{ margin: "10px 0px" }}>
                    <hr className="hr-icons" />
                  </Box>
                </Box>
                <Typography sx={{ textAlign: "justify" }}>
                  {e.content}
                </Typography>
              </Box>
            </Grid>
          ))}
        </Grid>
      </Container>
    </Box>
  );
}

export default Adventages;
